// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzU0RW0fymJQTzol79a5jbz7_A6DSRT6k',
    appId: '1:193426112234:web:46ea6c8a5f48593254a193',
    messagingSenderId: '193426112234',
    projectId: 'envirementapp',
    authDomain: 'envirementapp.firebaseapp.com',
    storageBucket: 'envirementapp.appspot.com',
    measurementId: 'G-3E26X2Q230',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebfWI4eyCd66PCKm_qgDCsWhAm1hESxA',
    appId: '1:193426112234:android:9108a765571b9b0754a193',
    messagingSenderId: '193426112234',
    projectId: 'envirementapp',
    storageBucket: 'envirementapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu99E2Ie8UVHnemNsvj68f23cZh2t9NXE',
    appId: '1:193426112234:ios:e45dc74bca412d2154a193',
    messagingSenderId: '193426112234',
    projectId: 'envirementapp',
    storageBucket: 'envirementapp.appspot.com',
    iosClientId: '193426112234-gt2rokg6pqobd3oolmd1kev8ccv7f9bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu99E2Ie8UVHnemNsvj68f23cZh2t9NXE',
    appId: '1:193426112234:ios:e45dc74bca412d2154a193',
    messagingSenderId: '193426112234',
    projectId: 'envirementapp',
    storageBucket: 'envirementapp.appspot.com',
    iosClientId: '193426112234-gt2rokg6pqobd3oolmd1kev8ccv7f9bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
